name: CI/CD Pipeline
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Deploy to Azure
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.AZURE_VM_IP }}
        username: abbassi.maram          # <- corrigé ici
        key: ${{ secrets.AZURE_VM_SSH_KEY }}
        script: |
          # Vérifie ou crée le répertoire
          cd /home/abbassi.maram || mkdir -p /home/abbassi.maram
          cd /home/abbassi.maram
          
          # Supprime et recrée le répertoire du projet
          rm -rf Pfe
          git clone https://github.com/AbassiMaram/Pfe.git Pfe
          
          # Entre dans le répertoire et exécute Docker
          cd Pfe
          docker-compose down || true
          
          # Supprimer anciennes images pour éviter les conflits
          docker image rm frontend-image:latest backend-image:latest || true
          
          # Déployer les nouvelles images
          docker-compose up -d --build
          
          echo "Deployment completed successfully"

