name: Deploy to Azure
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to VM
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.AZURE_VM_IP }}
        username: ${{ secrets.AZURE_VM_USERNAME }}
        key: ${{ secrets.AZURE_VM_SSH_KEY }}
        script: |
          cd /home/abbassi.maram || mkdir -p /home/abbassi.maram
          cd /home/abbassi.maram
          rm -rf Pfe
          git clone https://github.com/AbassiMaram/Pfe.git Pfe
          cd Pfe
          echo "Deployment completed successfully"
